// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seotamkqrwhlryefbegi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlb3RhbWtxcndobHJ5ZWZiZWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjE4NDQsImV4cCI6MjA3MTUzNzg0NH0.T39Dp5nikfIGXquI-xRuy588egHquW06MUZ3fs1ULsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});